const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const electron = fs.readFileSync(path.join(root, 'clients', 'electron', 'main.js'), 'utf8');
const webview = fs.readFileSync(path.join(root, 'clients', 'webview2', 'Program.cs'), 'utf8');
const workflow = fs.readFileSync(path.join(root, '.github', 'workflows', 'release.yml'), 'utf8');
const config = fs.readFileSync(path.join(root, 'src', 'config.js'), 'utf8');
const electronPackage = JSON.parse(fs.readFileSync(path.join(root, 'clients', 'electron', 'package.json'), 'utf8'));
const rootPackage = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));

assert.match(electron, /findFreePort/);
assert.match(electron, /LOCAL_MODEL_GATEWAY_FORCE_SETTINGS: 'true'/);
assert.match(electron, /LOCAL_MODEL_GATEWAY_FORCE_PORT: String\(gatewayPort\)/);
assert.match(electron, /gatewayProcess\.once\('error'/);
assert.match(electron, /desktop-port-settings\.json/);
assert.match(electron, /端口设置/);
assert.match(electron, /mode === 'fixed'/);
assert.match(electron, /ELECTRON_RUN_AS_NODE: '1'/);
assert.doesNotMatch(electron, /const PORT = 8787/);
assert.match(webview, /FindFreePortAsync/);
assert.match(webview, /LOCAL_MODEL_GATEWAY_FORCE_SETTINGS/);
assert.match(webview, /LOCAL_MODEL_GATEWAY_FORCE_PORT/);
assert.match(webview, /EnableRaisingEvents/);
assert.match(webview, /desktop-port-settings\.json/);
assert.match(webview, /ShowPortSettings/);
assert.match(webview, /固定自定义端口/);
assert.doesNotMatch(webview, /const int Port = 8787/);
assert.match(config, /LOCAL_MODEL_GATEWAY_FORCE_SETTINGS/);
assert.match(workflow, /gateway\/src\/server\.js/);
assert.match(workflow, /gateway\/public\/index\.html/);
assert.equal(electronPackage.version, rootPackage.version);
assert.match(fs.readFileSync(path.join(root, 'clients', 'electron', 'package.json'), 'utf8'), /preload\.js/);
console.log('desktop client tests passed');